### ISSUE TITLE
Line Wrapping

### ISSUE THREAD

**Issue by timoxley** [arjunmehta/node-columns#1]
The text in the gif seems to be very broken, appears to be due to no line wrapping. Should probably support line wrapping.

> We cannot ask goes through two point with things called "st property of being uniq

![image](https://cloud.githubusercontent.com/assets/43438/5831898/94140a54-a176-11e4-8bdb-6e5f0363d98a.png)

**Comment by arjunmehta** [comment]
You're absolutely right! No line wrapping support yet but definitely planned.
The text in this particular gif is two distinct lines from the `txt` file being streamed.

Thanks @timoxley! If you feel adventurous, feel free to look around. I'll try and do this one today.

**Comment by arjunmehta** [comment]
@timoxley https://github.com/arjunmehta/node-columns#line-wrapping
Try the `book.js` example and see what you think. It still looks funny because the txt file has its own line breaks. I need to find some txt examples that do not have their own line breaks. :)

**Comment by timoxley** [comment]
:+1:  oh nice.
